name="C#"
website="http://www.ecma-international.org/publications/standards/Ecma-334.htm"

[HelloWorld]
code = """
using System;

public class Program
{
  public static void Main()
  {
    Console.WriteLine("Hello, World!");
  }
}
"""

[Comment]
code = """
// single line
/*
multi-line
*/
"""

[Variable]
code = """
int a = 1;
int b = 2, c = 3;
"""

[Function]
code = """
public static A identity<A>(A x) {
    return x;
}

public static B first<A, B>(A x)
    where A: Enumrable<B>, B: Nullable {
    var iter = x.GetEnumerator();
    return iter.next();
}
"""
