name="Rust"
website="https://www.rust-lang.org/"

[HelloWorld]
code = """
fn main() {
  println!("Hello, World!");
}
"""

[Comment]
code = """
// single line
/*
multi-line
*/
"""

[Literals]
code = """
'H' //Character
"hello" //String
r#""hello""# //Raw string
r##"foo #"# bar"## //Raw string
b'H' //Byte
b"hello" //Byte string
br#"hello"# //Raw byte string

// Number literals
98_222	//Decimal integer
0xff	//Hex integer
0o77	//Octal integer
0b1111_0000	//Binary integer
123.0E+77 //Floating-point

//Boolean literals
true
false
"""

[Variable]
code = """
// immutable binding
let a = 1;

// mutable binding
let mut b = 2;
"""

[Function]
code = """
pub fn identity<A>(x:A) -> A {
    x
}

pub fn first<A, B>(x: A) -> Option<B>
    where A: IntoIterator<Item = B> {
    let mut iter = x.into_iter();
    if let Some(one) = iter.next() {
        Some(one)
    } else {
        None
    }
}
"""
